name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: pip
      - run: |
          pip install --upgrade -r "${GITHUB_WORKSPACE}/dev-requirements.txt"
          autoflake --remove-all-unused-imports --recursive --remove-unused-variables "src"
          isort --check "src"

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          cache: pip
      - run: |
          pip install --upgrade -r "${GITHUB_WORKSPACE}/dev-requirements.txt"
          mypy "src"
          flake8 "src" --ignore=E501,W503,E203,E402
          black "src" --check -l 80
